#!/usr/bin/env node
/**
 * Jarvis Reflection Script
 * Reads .jarvis/memory.json, finds high-confidence learned rules,
 * and writes them back into CLAUDE.md under a "## Learned Rules" section.
 *
 * Runs automatically via the Stop hook in .claude/settings.json.
 * Can also be run manually: node scripts/reflect.js
 */

const fs = require("fs");
const path = require("path");

const ROOT      = path.join(__dirname, "..");
const MEM_PATH  = path.join(ROOT, ".jarvis", "memory.json");
const CLAUDE_MD = path.join(ROOT, "CLAUDE.md");

// ── Load memory ───────────────────────────────────────────────────────────────

if (!fs.existsSync(MEM_PATH)) {
  process.stderr.write("Jarvis: no memory yet — nothing to reflect on.\n");
  process.exit(0);
}

let memory;
try {
  memory = JSON.parse(fs.readFileSync(MEM_PATH, "utf8"));
} catch {
  process.stderr.write("Jarvis: could not parse memory.json — skipping reflection.\n");
  process.exit(0);
}

const rules = (memory.rules || []).filter(r => (r.confidence || 0) >= 0.6);
const dismissed = memory.dismissals || [];
const actions   = memory.actions   || [];

// ── Build summary ─────────────────────────────────────────────────────────────

const lines = [
  "",
  "## Learned Rules",
  `_Auto-generated by Jarvis reflection engine · ${new Date().toISOString().slice(0, 10)}_`,
  "",
];

if (rules.length === 0) {
  lines.push("_No high-confidence rules yet. Keep using Jarvis to build up patterns._");
} else {
  for (const r of rules) {
    const pct = Math.round((r.confidence || 0) * 100);
    if (r.type === "auto-suppress") {
      lines.push(`- **Auto-suppress** \`${r.id}\`: ${r.reason} (${pct}% confidence)`);
    } else if (r.type === "unreliable-action") {
      lines.push(`- **Unreliable action** \`${r.action}\`: ${r.reason} (${pct}% confidence)`);
    } else {
      lines.push(`- **${r.type}** \`${r.id}\`: ${r.reason} (${pct}% confidence)`);
    }
  }
}

// Stats footer
lines.push("", `_Memory: ${dismissed.length} dismissals · ${actions.length} actions · ${memory.snapshots?.length || 0} snapshots_`);

// ── Write to CLAUDE.md ────────────────────────────────────────────────────────

if (!fs.existsSync(CLAUDE_MD)) {
  process.stderr.write("Jarvis: CLAUDE.md not found — skipping reflection write.\n");
  process.exit(0);
}

let claudeMd = fs.readFileSync(CLAUDE_MD, "utf8");

// Remove any existing Learned Rules section before rewriting
claudeMd = claudeMd.replace(/\n## Learned Rules[\s\S]*$/, "").trimEnd();

fs.writeFileSync(CLAUDE_MD, claudeMd + "\n" + lines.join("\n") + "\n");

const msg = rules.length > 0
  ? `Reflected ${rules.length} rule${rules.length !== 1 ? "s" : ""} into CLAUDE.md`
  : "Reflection complete — no rules yet";

process.stderr.write(`📋 Jarvis: ${msg}\n`);
